# Generated by Django 4.2.6 on 2025-02-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('USDC', 'USD Coin'), ('LTC', 'Litecoin')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='coin_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('price_change_percent_24h', models.DecimalField(decimal_places=8, max_digits=32)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=32)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=32)),
                ('num_trades', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='analytics.coin')),
            ],
            options={
                'indexes': [models.Index(fields=['-close_time'], name='analytics_m_close_t_749830_idx')],
            },
        ),
    ]
