# Generated by Django 4.2.6 on 2025-03-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_coin_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdata',
            options={'ordering': ['-close_time']},
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='analytics_m_close_t_749830_idx',
        ),
        migrations.AddField(
            model_name='marketdata',
            name='bb_lower',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='bb_middle',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='bb_upper',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd_hist',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd_signal',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='rsi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='taker_buy_base_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='taker_buy_quote_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='close_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='high_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='low_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='open_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='price_change_percent_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('symbol', 'close_time')},
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['symbol', 'close_time'], name='analytics_m_symbol__9b2de6_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['close_time'], name='analytics_m_close_t_d621ff_idx'),
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='created_at',
        ),
    ]
