# Generated by Django 5.1.7 on 2025-03-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_marketdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='atr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='williams_r',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
