# Generated by Django 5.1.7 on 2025-03-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reddit_id', models.CharField(max_length=255, unique=True)),
                ('symbol_id', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('post_num_comments', models.IntegerField()),
                ('post_ups', models.IntegerField()),
                ('post_author_karma', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_redditpost',
                'indexes': [models.Index(fields=['reddit_id'], name='analysis_re_reddit__48135a_idx'), models.Index(fields=['created_at'], name='analysis_re_created_551de6_idx')],
            },
        ),
    ]
