# Generated by Django 5.1.7 on 2025-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='sentiment_label',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
